# Generated by Django 3.0.5 on 2020-06-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subeer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'verbose_name': 'Serial'},
        ),
        migrations.RemoveField(
            model_name='serial',
            name='poster',
        ),
        migrations.AlterField(
            model_name='episode',
            name='season_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subeer.Season', verbose_name='Season_is'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='url',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='serial_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subeer.Serial', verbose_name='Serial_id'),
        ),
    ]
