# Generated by Django 3.0.2 on 2020-06-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subeer', '0002_auto_20200616_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='season_id',
        ),
        migrations.AddField(
            model_name='episode',
            name='serial_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subeer.Serial', verbose_name='Serial_id'),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
