# Generated by Django 3.0.2 on 2020-06-16 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subeer', '0003_auto_20200616_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='date_of_release',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of premiere'),
        ),
        migrations.AddField(
            model_name='serial',
            name='value',
            field=models.SmallIntegerField(default=0, verbose_name='Значение'),
        ),
    ]
