# Generated by Django 3.0.2 on 2020-06-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subeer', '0004_auto_20200616_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serial',
            old_name='value',
            new_name='rate',
        ),
    ]
