# Generated by Django 3.0.2 on 2020-06-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subeer', '0006_episode_date_of_adding'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.BigIntegerField(default=1),
        ),
    ]
