# Generated by Django 3.0.7 on 2020-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subeer', '0007_episode_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIO', models.CharField(max_length=100)),
                ('Issue', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('date_issue', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
