# Generated by Django 3.0.7 on 2020-07-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subeer', '0008_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='url',
            field=models.SlugField(max_length=130),
        ),
    ]
